using System;

namespace ProjectEuler
{
    class Program
    {
        static void Main(string[] args)
        {
            Solutions solutions = new Solutions();

            Console.WriteLine("Problem 1 - Multiples of 3 and 5");
            Console.WriteLine("If we list all the natural numbers below 10 that are multiples of 3 or 5, " +
                "we get 3, 5, 6 and 9.The sum of these multiples is 23." +
                "\nFind the sum of all the multiples of 3 or 5 below 1000.");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem1());

            Console.WriteLine();
            Console.WriteLine("Problem 2 - Even Fibonacci numbers");
            Console.WriteLine("Each new term in the Fibonacci sequence is generated by adding the previous " +
                "two terms.By starting with 1 and 2, the first 10 terms will be:" +
                "\n1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ..." +

                "\nBy considering the terms in the Fibonacci sequence whose values do not exceed four million, " +
                "find the sum of the even-valued terms.");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem2());


            Console.WriteLine();
            Console.WriteLine("Problem 3 - Largest prime factor");
            Console.WriteLine("The prime factors of 13195 are 5, 7, 13 and 29." +
                "What is the largest prime factor of the number 600851475143 ?");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem3());

            Console.WriteLine();
            Console.WriteLine("Problem 4 - Largest palindrome product");
            Console.WriteLine("A palindromic number reads the same both ways.The largest palindrome made from " +
                "the product of two 2 - digit numbers is 9009 = 91 × 99. Find the largest palindrome made from the " +
                "product of two 3 - digit numbers.");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem4());

            Console.WriteLine();
            Console.WriteLine("Problem 5 - Smallest multiple");
            Console.WriteLine("2520 is the smallest number that can be divided by each of the numbers from 1 to 10 " +
                "without any remainder. What is the smallest positive number that is evenly divisible by all of the " +
                "numbers from 1 to 20 ?");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem5());

            Console.WriteLine();
            Console.WriteLine("Problem 6 - Sum square difference");
            Console.WriteLine("The sum of the squares of the first ten natural numbers is," +
                "The square of the sum of the first ten natural numbers is," +
                "Hence the difference between the sum of the squares of the first ten natural numbers and the square of the sum is." +
                "Find the difference between the sum of the squares of the first one hundred natural numbers and the square of the sum.");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem6());

            Console.WriteLine();
            Console.WriteLine("Problem 7 - 10001st prime");
            Console.WriteLine("By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13." +
                "What is the 10 001st prime number ?");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem7());

            Console.WriteLine();
            Console.WriteLine("Problem 8 - Largest product in a series");
            Console.WriteLine("The four adjacent digits in the 1000-digit number that have the greatest product are 9 × 9 × 8 × 9 = 5832." +
                "Find the thirteen adjacent digits in the 1000-digit number that have the greatest product. What is the value of this product?");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem8());

            Console.WriteLine();
            Console.WriteLine("Problem 9 - Special Pythagorean triplet");
            Console.WriteLine("A Pythagorean triplet is a set of three natural numbers, a < b < c, for which," +
                "a2 + b2 = c2" +
                "For example, 32 + 42 = 9 + 16 = 25 = 52." +
                "There exists exactly one Pythagorean triplet for which a +b + c = 1000." +
                "Find the product abc.");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem9());

            Console.WriteLine();
            Console.WriteLine("Problem 10 - Summation of primes");
            Console.WriteLine("The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17." +
                "Find the sum of all the primes below two million.");
            Console.WriteLine();
            Console.WriteLine("Solution is: {0}", solutions.Problem10());
        }
    }
}
